Feature/share button components
razrabs-media/journal pull request #11
Opened 2022-03-24 06:57 UTC by alkov-dev

Добавил новый компонент Web Share Api в папке journal\entities\posts\ui\article\index.tsx  
Также поместил его в папке journal\entities\posts\ui\webShare\WebShare.tsx

2022-03-24 08:03 UTC, evist0 commented on package.json
> +    "sass": "^1.49.9"
на проекте используется emotion. тащить sass не надо

2022-03-24 08:04 UTC, evist0 commented on shared/ui/image/index.tsx
> +    {props.src !== undefined && (
props.src === undefined ? <ImgNotFound/> : <StyledImage>

2022-03-24 08:04 UTC, evist0 commented on tsconfig.json
> +, "entities/posts/ui/webShare/WebShare.jsx"  ],
зачем?

2022-03-24 08:05 UTC, evist0 commented on package.json
> +    "react-web-share": "^1.1.5",
я думаю либа не нужна, достаточно просто поместить ссылку в буффер обмена

2022-03-24 08:05 UTC, evist0 commented on entities/posts/ui/webShare/WebShare.tsx
> +import styles from './WebShare.module.scss'
используй emotion

2022-03-24 08:05 UTC, evist0 commented on entities/posts/ui/webShare/WebShare.module.scss
> +.iconButton {
используй emotion

2022-03-24 08:06 UTC, evist0 commented on entities/posts/ui/webShare/WebShare.tsx
> +import React from 'react'
Сделай просто компонент ```<ShareIcon>``` внутри ```shared/ui/shared-icon```. берёт на вход компонент svg иконки и событие onClick

2022-03-24 08:06 UTC, evist0 commented on entities/posts/ui/webShare/WebShare.module.scss
> +.iconButton {
нейминг файлов через кебаб кейс по всему проекту

2022-03-24 08:07 UTC, evist0 requested changes
исправляй)

2022-03-24 08:09 UTC, evist0 commented on entities/posts/ui/aside/index.tsx
> -
почему удалил отступ?

2022-03-24 08:09 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +import styles from './styles.module.scss'
emotion

2022-03-24 08:10 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +      <div className={styles.preview__container}>
зачем столько дивов?

2022-03-24 08:10 UTC, evist0 commented on entities/posts/ui/article/styles.module.scss
> +}
emotion

2022-03-24 08:10 UTC, evist0 commented on shared/ui/image/index.tsx
> +const ImgNotFound = () => (
почему в пулл реквесте по кнопке поделиться присутсвует код из пулл реквеста по картинке?

2022-03-24 08:11 UTC, evist0 commented on shared/ui/image/index.tsx
> +const ImgNotFound = () => (
можно сразу импортить svg как реакт компонент

2022-03-24 08:21 UTC, default-razrab commented on entities/posts/ui/webShare/WebShare.tsx
> +          <svg
А это чего?

2022-03-24 08:24 UTC, alkov-dev commented on entities/posts/ui/aside/index.tsx
> -
По невнимательности)

2022-03-24 08:28 UTC, alkov-dev commented on entities/posts/ui/webShare/WebShare.tsx
> +          <svg
Я плагин использовал, и чтобы он работал нужна кнопка, пришлось поместить туда svg)

2022-03-24 12:27 UTC, evist0 requested changes

2022-03-24 12:27 UTC, evist0 commented on shared/ui/shared-icon/Share-icon.svg
> +<svg width="12" height="12" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
с маленькой буквы название файла)

2022-03-24 12:27 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +      <div>
я думаю, что второй див лишний + пробелы, кажется, ни к чему

2022-03-24 12:27 UTC, evist0 commented on shared/ui/image/index.tsx
> +const ImgNotFound = () => (
притащи свг к shared/ui/image и импортни как компонент

2022-03-24 12:27 UTC, evist0 commented on shared/ui/shared-icon/index.tsx
> +import shareIcon from './Share-icon.svg'
а вот название импортируемого компонента - с большой `ShareIcon` )

2022-03-24 12:27 UTC, evist0 commented on tsconfig.json
> +, "entities/posts/ui/webShare/WebShare.jsx"  ],
всё еще не убрал(

2022-03-24 12:27 UTC, evist0 commented on shared/ui/shared-icon/index.tsx
> +const ShareIcon = () => <StyledShareIcon onClick={handleShareButton} />
onClick сделай приходящим пропсом

функцию копирования в буфер прокинь в месте использования (на странице чтения) + убери ненужные обработки промисов, консоль логи

2022-03-25 06:14 UTC, alkov-dev commented on shared/ui/shared-icon/index.tsx
> +import shareIcon from './Share-icon.svg'
=)

2022-03-25 06:15 UTC, alkov-dev commented on shared/ui/shared-icon/index.tsx
> +const ShareIcon = () => <StyledShareIcon onClick={handleShareButton} />
Почему часть кода не исправилась, я же переделал

2022-03-25 12:35 UTC, evist0 requested changes
почти идеально

2022-03-25 12:35 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +import ShareIcon from 'shared/ui/shared-icon'
название папки shared-icon, компонент - ShareIcon.

переименуй папку в `share-icon`

2022-03-25 12:35 UTC, evist0 commented on entities/posts/model/GetPost.graphql
> -    description,
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/32814970/160120768-5fc16ce7-313f-49fd-97e7-f958fefd65c8.png">

с бэка есть и описание и контент. убрали только publicationDate

2022-03-25 12:35 UTC, evist0 commented on shared/ui/shared-icon/index.tsx
> +type handleShareButtonType = {
```
type ShareIconProps =  Omit<HTMLButtonProps, 'children'> (или как-то так)
```

у нас же это КНОПКА поделиться, так что застилизуй кнопку, закинь в неё svg и прокидывай все пропсы пришедшие сверху в эту кнопку

2022-03-25 12:35 UTC, evist0 commented on shared/ui/image/index.tsx
> +    {props.src !== undefined && (
всё еще не исправлено

2022-03-25 12:35 UTC, evist0 commented on shared/ui/shared-icon/Share-icon.svg
> +<svg width="12" height="12" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
всё еще не исправлено)

2022-03-25 12:35 UTC, evist0 commented on shared/ui/image/index.tsx
> +const ImgNotFound = () => (
всё еще не исправлено)

2022-03-25 12:35 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +        <ShareIcon handleShareButton={handleShareButton} />
посмотри комменты к `share-icon/index.tsx`, хотелось бы чтобы пропсы были как у кнопки -> хэндлер будет прокидываться в `onClick`

2022-03-25 12:35 UTC, evist0 commented on entities/posts/ui/article/index.tsx
> +      <div>
а зачем тут этот див?

2022-03-25 12:35 UTC, evist0 commented on shared/ui/shared-icon/index.tsx
> +}): JSX.Element => <StyledShareIcon onClick={handleShareButton} />
Не надо указывать тип, который вернётся из функции, по типу самой функции `React.FC<ShareIconProps` это итак понятно.

К тому же, уместнее было бы использовать `React.VFC`, а не `React.FC`, так как у нас нет `children` в пропсах

2022-03-27 09:13 UTC, evist0 approved these changes

2022-03-27 09:17 UTC, evist0 approved these changes

2022-03-27 09:19 UTC, merged