feat: fixed header in app
razrabs-media/journal pull request #20
Opened 2022-03-29 07:34 UTC by alkov-dev

Зафиксировал шапку в приложении

2022-03-29 09:21 UTC, evist0 requested changes
https://t.me/c/1362424299/4042

2022-03-29 13:34 UTC, default-razrab commented on pages/_app.tsx
> +      <Grid>
боди и грид можно объеденить

2022-03-29 13:34 UTC, default-razrab commented on pages/_app.tsx
> +  height: 100vh;
высоты тут не надо

2022-03-29 13:37 UTC, default-razrab commented on pages/_app.tsx
> +  height: 100vh;
Она должна быть в grid.  Где то есть компонен, что растянут на весь экран вот он и должен быть базисом)

2022-03-29 13:37 UTC, default-razrab commented on pages/_app.tsx
> +  grid-template-areas:
посмотри просто `grid-template` он полеезнее

2022-03-30 21:32 UTC, default-razrab requested changes

2022-03-30 21:32 UTC, default-razrab commented on pages/_app.tsx
> +      <Grid>
+1

2022-03-31 16:12 UTC, default-razrab approved these changes

2022-03-31 16:14 UTC, evist0 approved these changes

2022-04-01 04:59 UTC, evist0 approved these changes

2022-04-01 05:00 UTC, merged