preview images fixed
razrabs-media/journal pull request #26
Opened 2022-03-31 20:29 UTC by YaroslavBorshevsky812

поправил отображение картинок в превью и в контентной части

2022-04-01 07:24 UTC, evist0 requested changes

2022-04-01 11:13 UTC, default-razrab requested changes

2022-04-01 11:13 UTC, default-razrab commented on shared/ui/image/index.tsx
>    max-height: 600px;
Максимальная высота в цифрах это плохо, попробуй сделать масимальную высоту как форму квадрата.

2022-04-01 11:13 UTC, default-razrab commented on shared/ui/markdown-renderer/index.tsx
> +    object-fit: contain;
Я думаю маркдаун править это не в этой задаче надо.

2022-04-04 08:51 UTC, YaroslavBorshevsky812 commented on shared/ui/markdown-renderer/index.tsx
> +    object-fit: contain;
Поправил

2022-04-05 03:35 UTC, evist0 commented
у тебя ветка актуальность потеряла, там файлы переносили в `src` ребейзнись)

2022-04-05 18:34 UTC, default-razrab requested changes

2022-04-05 18:34 UTC, default-razrab commented on shared/ui/markdown-renderer/index.tsx
> +    object-fit: contain;
тут в принципе всё что в diff убрать надо

2022-04-05 18:34 UTC, default-razrab commented on shared/ui/image/index.tsx
> +  aspect-ratio: 1/1;
Хорошее решение, но прямоугольную форму не умеет

2022-04-09 21:05 UTC, default-razrab approved these changes

2022-04-09 21:05 UTC, merged