Numerical inflection has been improved
razrabs-media/journal pull request #295
Opened 2022-08-01 20:53 UTC by batyshkaLenin

2022-08-01 21:07 UTC, CommanderTvis submitted a review, later dismissed

2022-08-01 21:35 UTC, default-razrab requested changes

2022-08-01 21:35 UTC, default-razrab commented on src/entities/user-content/ui/user-info/index.tsx
> +const countFormatter = (titles: string[]) => {
предлагаю назвать Pluralization, и вынести в `shared/lib` 

возможно можно сделать компонент базирующийся на typography

2022-08-01 21:35 UTC, default-razrab commented on src/entities/user-content/ui/user-info/index.tsx
> +const countFormatter = (titles: string[]) => {
и предложил бы создать тип объекта `{ zero/many, one, few }` (zero/many вроде всегда одно и тоже) когда нибудь в будущем вставим `i18next`

2022-08-01 21:58 UTC, default-razrab requested changes

2022-08-01 21:58 UTC, default-razrab commented on src/entities/user-content/ui/user-info/index.tsx
> +  const formattedComments = pluralize({ zero: 'коммент написан', one: 'коммента написано', few: 'комментов написано' }, commentsCount)
`0 комментов, 1 коммент, 2 коммента` тексты немного не сходятся

2022-08-01 21:59 UTC, default-razrab commented on src/entities/user-content/ui/user-info/index.tsx
> +import { pluralize } from "shared/lib"
Ещё бы `yarn lint --fix` прогнать)

2022-08-01 22:03 UTC, batyshkaLenin commented on src/entities/user-content/ui/user-info/index.tsx
> +  const formattedComments = pluralize({ zero: 'коммент написан', one: 'коммента написано', few: 'комментов написано' }, commentsCount)
Всё верно, но нейминг неправильный.
https://replit.com/@MacOSO/pluralize?v=1

2022-08-01 22:11 UTC, default-razrab commented on src/entities/user-content/ui/user-info/index.tsx
> +  const formattedComments = pluralize({ zero: 'коммент написан', one: 'коммента написано', few: 'комментов написано' }, commentsCount)
К тому и веду, что нейминг бы поправить)

2022-08-02 08:14 UTC, default-razrab approved these changes

2022-08-02 08:15 UTC, merged