Improve semantic tags and tab navigation
razrabs-media/journal pull request #309
Opened 2022-08-02 19:11 UTC by ninedev-i

Улучшил навигацию по нажатию на таб.
Заменил некоторые теги на более верные с точки зрения семантики.
Теперь модальные окна рендерятся только после открытия, из-за этого нет фокуса на скрытые элементы.
Добавил подсветку при фокусе на кнопку авторизации.

2022-08-03 06:18 UTC, philippranzhin approved these changes

2022-08-04 10:00 UTC, default-razrab commented
Был похожий пр с похожими правками, предлагаю актуализировать пр

2022-08-04 10:00 UTC, default-razrab requested changes

2022-08-04 10:03 UTC, ninedev-i commented on components/packages/clock/src/index.tsx
> +const StyledTime = styled.time`
Можно https://styled-components.com/docs/basics#getting-started

2022-08-04 10:03 UTC, ninedev-i commented
> Был похожий пр с похожими правками, предлагаю актуализировать пр

А можно ссылку, а то я не нашел.

2022-08-04 13:23 UTC, default-razrab commented
> > Был похожий пр с похожими правками, предлагаю актуализировать пр
> 
> А можно ссылку, а то я не нашел.

ок, похожие вещи в др файлах были

2022-08-04 13:32 UTC, batyshkaLenin commented
@default-razrab у меня про другое было, у меня микроразметка именно

2022-08-04 13:33 UTC, ninedev-i commented on components/packages/clock/src/index.tsx
> +const StyledTime = styled.time`
Ок, согласен, поправил.

2022-08-04 15:41 UTC, default-razrab requested changes

2022-08-04 15:50 UTC, ninedev-i commented on src/widgets/header/ui/header/index.tsx
> +      {open && <Auth open={open} ref={ref} onClose={falsy} />}
Без этой проверки у тебя отрисовывается содержимое модалки, даже когда ее никто не открывал (зачем рисовать сотню комментариев, когда с большей вероятностью их пользователь даже не откроет).
Да и навигация через таб фокусируется на невидимых элементах.

Никакие хуки не ломаются. Хуки начинают работать с первым рендером, который происходит когда open === true.

2022-08-04 19:30 UTC, default-razrab commented on src/widgets/header/ui/header/index.tsx
> +      {open && <Auth open={open} ref={ref} onClose={falsy} />}
Это модалка для авторизации, там комментов нет, а есть хук который на этой переменной дазейблит скрол, и если там не придёт false он скрол не откроет. Это не совсем верное решение, но текущий пр может сломать всё)

2022-08-05 18:26 UTC, ninedev-i commented on src/widgets/header/ui/header/index.tsx
> +      {open && <Auth open={open} ref={ref} onClose={falsy} />}
Можно было бы не костылять так, если бы у модалка была нативным диалогом ;)

2022-08-05 19:12 UTC, ninedev-i commented on src/widgets/header/ui/header/index.tsx
> +      {open && <Auth open={open} ref={ref} onClose={falsy} />}
Убрал проверку на open, но добавил пробрасывание этой пропсы внутрь компонентов, чтобы выставлять tabindex в зависимости от нее.

2022-08-05 21:28 UTC, default-razrab approved these changes

2022-08-05 21:28 UTC, merged