draft: feat: [help-needed] адаптивная вёрстка страницы чтения
razrabs-media/journal pull request #31
Opened 2022-04-01 19:33 UTC by evist0

2022-04-01 21:39 UTC, default-razrab requested changes

2022-04-01 21:39 UTC, default-razrab commented on shared/ui/typography/index.ts
> +// Webstorm не понимает, что там помимо строки может придти число
А зачем число?

2022-04-01 21:39 UTC, default-razrab commented on entities/posts/ui/post-reader/ui/index.tsx
> +      uid={props.uid}
Тут уж через деструктуризацию можно)

2022-04-01 21:39 UTC, default-razrab commented on entities/posts/ui/post-reader/ui/header/styled.ts
> +  position: absolute;
Кажется так себе решение)

2022-04-01 21:39 UTC, default-razrab commented on entities/posts/ui/post-reader/ui/header/index.tsx
> +            {format(props.publicationDate, 'dd MMMM, H:mm', {
В отдельный бы компонент засунуть дату

2022-04-02 01:17 UTC, evist0 commented on entities/posts/ui/post-reader/ui/header/styled.ts
> +  position: absolute;
Кажется, что, да, но других вариантов я пока не вижу.

Обязательно нужно чтобы в первой строке была только превью картинка и заголовок с описанием. 
(Чтобы белая линия равнялась с картинкой или была больше)

Если картинка больше, чем текст - то можно расположить дату на второй строке и все будет валидно, однако в том случае, когда текст будет больше картинки - располагаемая на второй строке дата поедет.

Так что закостылил пока что

2022-04-02 01:19 UTC, evist0 commented on shared/ui/typography/index.ts
> +// Webstorm не понимает, что там помимо строки может придти число
Там заголовок у статьи имеет размер 32, если не ошибаюсь, который не совпадает с теми, что в мапе.

Я сначала хотел тайпографи для него забрать, но заголовок то это h1, а типография нам даёт p :)

2022-04-02 01:21 UTC, evist0 commented on entities/posts/ui/post-reader/ui/index.tsx
> +      uid={props.uid}
Можно) но я чёт на днях где-то услышал, что деструктуризацию при пропс дриллинге использует только быдло 😎

Потому что становится менее наглядно какие пропсы куда уходят

2022-04-05 18:31 UTC, default-razrab requested changes

2022-04-05 18:31 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +        <div />
Интересная структура)

2022-04-05 18:31 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/styled.ts
> +
Нет смысла в таких отступах по коду не прослеживается закономерность) Выглядит как отступы в рандомных местах

2022-04-05 18:31 UTC, default-razrab commented on src/shared/ui/typography/index.ts
> +// Webstorm не понимает, что там помимо строки может придти число
Ты не используешь число оно не нужно)

2022-04-05 18:31 UTC, default-razrab commented on src/shared/ui/typography/index.ts
> +  text-decoration: none;
Я их вынес в глобал тут не надо

2022-04-09 20:38 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/floated-preview/styled.ts
> +  max-width: 1872px;
Думаю ширина тут не пригодится.

2022-04-09 20:38 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/index.tsx
> +    <>
Не люблю фрагменты в корне) Выглядит как насильное объединение независимых компонентов

2022-04-09 20:42 UTC, default-razrab commented on shared/ui/typography/index.ts
> +// Webstorm не понимает, что там помимо строки может придти число
в styled можно передать as="h1" и будет h1, из-за этого он стайлед был переделан первым. ) А если нужно будет 32, то мне кажется стоит добавить его как константу тоже, т.к. абс рандомные цифры размеров на мне нужны

2022-04-16 14:34 UTC, default-razrab approved these changes

2022-04-16 14:35 UTC, merged