Добавил микроразметку Schema.org
razrabs-media/journal pull request #313
Opened 2022-08-03 00:10 UTC by batyshkaLenin

И добавил отображение инициалов, вместо первых двух букв имени.

2022-08-03 06:19 UTC, philippranzhin approved these changes

2022-08-04 09:10 UTC, default-razrab requested changes

2022-08-04 09:10 UTC, default-razrab commented on src/shared/ui/date-ago/index.tsx
> +      <time dateTime={date} itemProp='datePublished'>
а нельзя в `Typography`  тег `time` передать?

2022-08-04 09:56 UTC, default-razrab approved these changes

2022-08-04 09:58 UTC, default-razrab approved these changes

2022-08-04 09:58 UTC, merged