feat: Добавил подсветку реплая при переходе к нему и анимировал ховер комментариев
razrabs-media/journal pull request #324
Opened 2022-08-03 20:34 UTC by gkopylovdev

closes #308 

https://user-images.githubusercontent.com/28918530/182706384-ae141b76-2145-487f-be99-a63fe00438e3.mp4

2022-08-03 20:36 UTC, gkopylovdev commented
По большей мере это база для будущей анимации подсветки. Имхо- подсветку и анимацию ховера еще стоит ковырять

2022-08-04 09:19 UTC, default-razrab requested changes

2022-08-04 09:19 UTC, default-razrab commented on components/packages/comments/src/styled.ts
> +type StyledCommentProps = {
в `types.ts` вынести бы

2022-08-04 09:19 UTC, default-razrab commented on components/packages/comments/src/index.tsx
> +export type CommentForwardedRef = HTMLDivElement & { highlight: () => void }
```suggestion
export type CommentForwardedRef = HTMLDivElement & { highlight: VoidFunction }
```
`+` в `types.ts` вынести бы

2022-08-04 09:19 UTC, default-razrab commented on components/packages/comments/src/index.tsx
> +    const internalRef = useRef<HTMLDivElement>(null)
Предлагаю сделать кастомный хук и вынести в файл `hooks`

2022-08-04 10:43 UTC, gkopylovdev commented on components/packages/comments/src/styled.ts
> +type StyledCommentProps = {
Точно ли стоит? Кмк стилевые типы, которые нигде больше не используются стоит хранить рядом со стилями, где этот тип применяется. Все таки в types обычно выносятся какие-то типы, которые могут где-то переиспользоваться вне этого модуля (по крайней мере на моей практике)
Не особо хочу влезать в спор, если скажешь "не, нихуя", то я фиксану)

2022-08-04 10:48 UTC, gkopylovdev commented on components/packages/comments/src/index.tsx
> +    const internalRef = useRef<HTMLDivElement>(null)
Не совсем понял зачем или не догнал в чем суть хука. Сейчас ты юзаешь `const internalRef = useRef<type>()`, а с кастомным хуком будет `const internalRef = useInternalRef<type>()`

2022-08-04 10:51 UTC, gkopylovdev commented on components/packages/comments/src/index.tsx
> +export type CommentForwardedRef = HTMLDivElement & { highlight: () => void }
fixed

2022-08-04 10:51 UTC, gkopylovdev commented
@default-razrab Часть комментов фиксанул, по части комментов отписал

2022-08-04 12:36 UTC, ninedev-i approved these changes

2022-08-04 14:21 UTC, default-razrab commented on components/packages/comments/src/index.tsx
> +    const internalRef = useRef<HTMLDivElement>(null)
Я имел в виду всю логику с хайлатом типо  `const { ref, isHighlighted} / [ ref, isHighlighted] = useHighlighted()`

2022-08-04 15:57 UTC, default-razrab requested changes

2022-08-04 15:57 UTC, default-razrab commented on components/packages/comments/src/styled.ts
> +type StyledCommentProps = {
Я думаю без типов становится код чище, а особенно когда типы большие и когда много компонентов.  А т.к. сложно определить какой тип большой и его стоит выносить, а какой маленький и можно оставить проще по дефолту выносить все

2022-08-04 19:13 UTC, gkopylovdev commented
@default-razrab Залил фиксы

2022-08-05 08:33 UTC, default-razrab approved these changes

2022-08-05 08:33 UTC, merged