Добавлены SEO мета-теги и манифест для PWA
razrabs-media/journal pull request #353
Opened 2022-08-05 20:26 UTC by batyshkaLenin

2022-08-05 20:31 UTC, philippranzhin submitted a review, later dismissed

2022-08-05 22:03 UTC, default-razrab commented on src/shared/lib/helmet/index.tsx
> +  const host = process.env.NEXT_PUBLIC_HOST
Несильно верю, что тут всё правильно работать будет, предлагаю 
```suggestion
   const isServerSide = typeof window === 'undefined'
   const host = (isServerSide ? serverRuntimeConfig : publicRuntimeConfig).HOST
```

И импорты добавить  
```
import getConfig from 'next/config'

const { publicRuntimeConfig, serverRuntimeConfig } = getConfig()
```

2022-08-05 22:06 UTC, default-razrab requested changes

2022-08-05 22:06 UTC, default-razrab commented on src/shared/lib/helmet/index.tsx
> +  const canonicalUrl = host + path
мб для верности через какой нибудь uri заджойнить или т.п.?

2022-08-05 22:16 UTC, batyshkaLenin commented on src/shared/lib/helmet/index.tsx
> +  const canonicalUrl = host + path
Тут уже не знаю как лучше поступить. Я так понимаю это для валидации URL, валидация предполагает что может быть ошибка. Что нам даст эта ошибка и что мы тогда будем считать cannonicalUrl если будет ошибка?

2022-08-05 22:19 UTC, batyshkaLenin commented
@default-razrab обрати внимание, я добавил заголовки к лентам и добавил брендированную пометку в конце заголовка статьи

2022-08-06 16:38 UTC, default-razrab approved these changes

2022-08-06 16:38 UTC, merged