feat: preview for telegram and twitter
razrabs-media/journal pull request #36
Opened 2022-04-07 18:46 UTC by YaroslavBorshevsky812

Сделал 400px, размера в дизайне нет.

2022-04-08 18:45 UTC, raantoniv commented on shared/api/types.ts
> +// 🛑 NOTICE: __generated__ folders should be added to .gitignore
@evist0 @YaroslavBorshevsky812 а зачем исключили из игнора?

2022-04-08 22:17 UTC, YaroslavBorshevsky812 commented on shared/api/types.ts
> +// 🛑 NOTICE: __generated__ folders should be added to .gitignore
Добавил, потом убрал. Недопонял. Исправлю

2022-04-09 02:47 UTC, evist0 commented
это я добавлял)
файл автогенерируемый, там линтер 1к+ ошибок находит)

2022-04-09 21:10 UTC, default-razrab requested changes

2022-04-09 21:10 UTC, default-razrab commented on src/pages/index.tsx
> +  previewUrl: '/src/shared/ui/logo/avatar.png',
Думаю нудно картинку в папку publiсk  положить

2022-04-09 21:10 UTC, default-razrab commented on shared/api/types.ts
> +// 🛑 NOTICE: __generated__ folders should be added to .gitignore
Сам файл удалить надо.

2022-04-09 21:10 UTC, default-razrab commented on .gitignore
> +/shared/api/
есть небольшой косяк в генерации, и путь поменяется убери пока из гит игнора, косяк поправиться в др пр

2022-04-09 21:29 UTC, default-razrab approved these changes

2022-04-09 21:29 UTC, merged