Добавлена поддержка Sitemap
razrabs-media/journal pull request #364
Opened 2022-08-07 18:35 UTC by batyshkaLenin

Closed #320

2022-08-07 18:40 UTC, batyshkaLenin commented on src/pages/posts/sitemap.xml/index.tsx
> +  const allPostsPromise = await Promise.all(
По хорошему это чепуха и нужен нормальный запрос с бэка, который будет брать n последних постов в принципе. Из всех фидов.

2022-08-07 18:41 UTC, batyshkaLenin commented on src/pages/posts/sitemap.xml/index.tsx
> +  const allPostsPromise = await Promise.all(
Но опять же, пока что, чисто для того чтобы поисковикам уже было что кушать сейчас это можно оставить и добавить чуть позже нормальный запрос.

2022-08-07 19:20 UTC, batyshkaLenin commented on src/pages/posts/sitemap.xml/index.tsx
> +  const allPostsPromise = await Promise.all(
Придумал что с этим сделать, разделил sitemap на sitemap для фидов (где ссылки на все фиды) и для каждого такого есть sitemap со всеми постами фида и корнем фида

2022-08-07 21:08 UTC, default-razrab requested changes

2022-08-07 21:08 UTC, default-razrab commented on package.json
> +    "next-sitemap": "^3.1.16",
```suggestion
    "next-sitemap": "3.1.16",
```

2022-08-07 23:02 UTC, GNMKR reviewed
Может имеет смысл также добавить sitemap для постов?

2022-08-08 05:52 UTC, batyshkaLenin commented
@GNMKR всё очень разумно, но для этого нужно делать запросы на GraphQL, а у меня пока нет доступа к бэку.

2022-08-08 08:04 UTC, philippranzhin approved these changes

2022-08-09 19:52 UTC, default-razrab approved these changes

2022-08-09 19:52 UTC, merged