Sticky aside layout
razrabs-media/journal pull request #419
Opened 2022-08-15 19:04 UTC by ninedev-i

Переверстал. Теперь Сайдбар отдельно от шапки.
Сайдбар прилипает, затеняется, появляется дополнительная информация

![image](https://user-images.githubusercontent.com/17778661/184699891-8acec483-1800-4629-bc95-bdb4a2b35dc6.png)

2022-08-15 19:09 UTC, batyshkaLenin commented
Я правильно понимаю, что это #254?

2022-08-15 19:10 UTC, ninedev-i commented
> Я правильно понимаю, что это #254?

Да, забыл прикрепить

2022-08-15 19:14 UTC, batyshkaLenin commented
![изображение](https://user-images.githubusercontent.com/8469236/184701609-5243abeb-f748-4fd7-a650-85d95d7c0d51.png)

2022-08-15 19:16 UTC, batyshkaLenin requested changes
![изображение](https://user-images.githubusercontent.com/8469236/184701833-68f17740-3c4a-4496-8e2e-2ac46a2dd80b.png)

2022-08-15 19:21 UTC, ninedev-i commented
> ![изображение](https://user-images.githubusercontent.com/8469236/184701833-68f17740-3c4a-4496-8e2e-2ac46a2dd80b.png)

fixed

2022-08-18 21:54 UTC, default-razrab commented
А можешь снять видео по сайд бару, реализацию поглядеть, а то есть крутая идея, и я думаю она не была нигде описана)

2022-08-18 22:13 UTC, ninedev-i commented
> А можешь снять видео по сайд бару, реализацию поглядеть, а то есть крутая идея, и я думаю она не была нигде описана)

Обновил description пра, см выше

2022-08-19 15:32 UTC, batyshkaLenin commented
@default-razrab была, в макетах и в ишуях от дизайнеров описана

2022-08-19 15:34 UTC, batyshkaLenin commented
![изображение](https://user-images.githubusercontent.com/8469236/185654715-c1b037c0-f4aa-47fa-a4b3-24970dc6ea72.png)
@ninedev-i блок судя по макету, должен быть затенён, и при наведении на всю яркость работать

2022-08-19 15:40 UTC, ninedev-i commented
> ![изображение](https://user-images.githubusercontent.com/8469236/185654715-c1b037c0-f4aa-47fa-a4b3-24970dc6ea72.png) @ninedev-i блок судя по макету, должен быть затенён, и при наведении на всю яркость работать

если я правильно понял макеты, то он затеняется только в том случае, если экран прокручен ниже блока с тегами

2022-08-19 15:45 UTC, batyshkaLenin commented
Ошибочка вышла, всё окей!

2022-08-19 21:03 UTC, batyshkaLenin submitted a review, later dismissed

2022-08-22 18:18 UTC, default-razrab requested changes

2022-08-22 18:18 UTC, default-razrab commented on src/shared/ui/share-button/lib/withCopyToClipboard.tsx
> +export interface ButtonProps
В типы бы вынести

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/styled.ts
> +export const ContentWrapper = styled.main<{ open: boolean }>`
open не используется

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/index.tsx
> +  const headerVisibilityRef = useRef()
Предлагаю вынести код в отдельный хук

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +export const PostHeader = forwardRef<HTMLDivElement, Props>((props) => {
Если реф не нужен то и forwardRef думаю стоит убрать

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/styled.ts
> +  @media screen and (max-width: 672px) {
Использовать бы значения из конфига

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/styled.ts
> +  @media screen and (max-width: 671px) {
Использовать бы значения из конфига

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/styled.ts
> +  @media screen and (max-width: 1920px) {
Использовать бы значения из конфига

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/index.tsx
> +  const [href, setHref] = useState('')
В хук бы вынести

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/index.tsx
> +export const Aside = forwardRef<HTMLDivElement, Props>((props) => {
forwardRef выглядит, что не нужен

2022-08-22 18:18 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/aside/index.tsx
> +export const DefaultShareButton = styled(Typography)`
в styled бы вынести

2022-08-22 19:20 UTC, ninedev-i commented on src/entities/posts/ui/post-reader/ui/aside/index.tsx
> +  const [href, setHref] = useState('')
Думаю здесь это избыточно

2022-08-22 20:52 UTC, default-razrab approved these changes

2022-08-22 20:52 UTC, merged