feat: markdown renderer updates
razrabs-media/journal pull request #43
Opened 2022-04-24 09:02 UTC by hamaddo

- fix: date-fns method changed
- fix: mobile version title description size

- - ![image](https://user-images.githubusercontent.com/37376939/164968765-bf1710dd-6bcb-464c-87f8-2dcec22a7f2a.png)
- - ![image](https://user-images.githubusercontent.com/37376939/164968788-53439f54-c4f9-424f-bd66-e13f5ad20717.png)
- - ![image](https://user-images.githubusercontent.com/37376939/164968829-da7fbfd2-362c-4b4f-966b-192789b9a93d.png)

2022-05-03 15:30 UTC, default-razrab requested changes

2022-05-03 15:30 UTC, default-razrab commented on src/shared/ui/typography/types.ts
> +export type Size = 'large' | 'medium' | 'small' | 'default'
А почему такое название размера:?

2022-05-03 15:30 UTC, default-razrab commented on src/shared/ui/typography/index.ts
> +  default: 20,
Можно добавить xl и не множко переименовать

2022-05-03 15:30 UTC, default-razrab commented on src/shared/ui/date-ago/index.tsx
> +    <Typography transparent uppercase as='span' style={{ lineHeight: '100%' }}>
Без прямой передачи стилей бы

2022-05-07 04:05 UTC, hamaddo commented on src/shared/ui/typography/types.ts
> +export type Size = 'large' | 'medium' | 'small' | 'default'
открыт к предложениям

2022-05-07 04:05 UTC, hamaddo commented on src/shared/ui/typography/index.ts
> +  default: 20,
тут уже есть `large` размер

2022-05-21 08:17 UTC, evist0 commented
@hamaddo есть кто живой? добивать будешь?

2022-05-22 21:21 UTC, default-razrab approved these changes

2022-05-22 21:22 UTC, merged