Feature/added current date
razrabs-media/journal pull request #44
Opened 2022-04-29 13:08 UTC by alkov-dev

Добавил отображение текущей даты и время

2022-05-01 15:15 UTC, default-razrab commented
А почему 2 картинки добавлены?

2022-05-01 15:15 UTC, default-razrab requested changes

2022-05-01 15:15 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +  setInterval(() => {
Лучше создать кастомный хук.

2022-05-01 15:15 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +  }, 60000)
60 секунд оно не всегда 60 секунд, и будут просадки иногда

2022-05-01 15:15 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +        <img alt='Текущая дата' src='/images/svg/ellipse.svg' />
А как для светлой темы будет? И так импортить не стоит

2022-05-01 15:15 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/styled.ts
> +
Для чего?

2022-05-01 17:04 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/styled.ts
> +
+++

2022-05-02 11:12 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +  setInterval(() => {
+++

2022-05-02 11:12 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +  const currentDate = useMemo(
+++

2022-05-02 11:13 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +  }, 60000)
+++

2022-05-02 11:13 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +        <img alt='Текущая дата' src='/images/svg/ellipse.svg' />
+++

2022-05-03 16:54 UTC, evist0 commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
> +              clicked={clicked}
может стоит вынести логику этого хука на уровень кнопки, чтобы удобнее было поддерживать компонент?

2022-05-18 14:05 UTC, alkov-dev commented on shared/api/types.ts
> +// 🛑 NOTICE: __generated__ folders should be added to .gitignore
+++

2022-05-21 08:16 UTC, evist0 commented
дублирует ПР #51 закрываю. разнесу чери-пиком

2022-05-21 08:16 UTC, closed without merging