fix: Фикс отображения кнопки "поделиться"
razrabs-media/journal pull request #443
Opened 2022-08-21 18:11 UTC by gkopylovdev

closes #434 

В хроме на вебе нет ShareAPI - там возникала такая проблема до фикса. На десктоп сафари ShareApi есть, на нужном разрешении кнопка "поделиться" будет работать корректно

Хром ширина веба
<img width="1075" alt="Снимок экрана 2022-08-21 в 23 04 57" src="https://user-images.githubusercontent.com/28918530/185804879-6a1929fd-a314-4904-9bb6-6ae9455e9bb3.png">

Хром ширина планшета
<img width="834" alt="Снимок экрана 2022-08-21 в 23 05 05" src="https://user-images.githubusercontent.com/28918530/185804883-fc0665fc-3fa7-4dd5-9923-bd28ae52d041.png">

Хром ширина мобилы 
<img width="514" alt="Снимок экрана 2022-08-21 в 23 05 12" src="https://user-images.githubusercontent.com/28918530/185804888-c4666c08-d47a-4cd9-b410-11096b819ca9.png">

Сафари ширина мобилы
<img width="611" alt="Снимок экрана 2022-08-21 в 23 07 08" src="https://user-images.githubusercontent.com/28918530/185804910-287495c9-fad0-43b6-bb4c-0fccdea666c4.png">

2022-08-22 07:26 UTC, batyshkaLenin commented
Судя по статье в мобильном хроме есть: [ссылка](https://caniuse.com/web-share)

2022-08-22 07:45 UTC, gkopylovdev commented
> Судя по статье в мобильном хроме есть: [ссылка](https://caniuse.com/web-share)

я и не спорю, но мобильное разрешение десктопного браузера не равно мобильному браузеру)

2022-08-22 21:01 UTC, default-razrab requested changes

2022-08-22 21:01 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +    setCanShare(!!navigator.canShare)
не очень понимаю для чего это?

2022-09-12 21:29 UTC, default-razrab approved these changes

2022-09-12 21:29 UTC, merged