fix: added max-with from markdown and title, added img style display-…
razrabs-media/journal pull request #60
Opened 2022-05-23 09:46 UTC by alkov-dev

Изменил свойство картинки в маркдауне и добавил максимальную ширину

2022-05-25 01:06 UTC, evist0 requested changes
Опять две задачки в одной ветке делаешь?:)

2022-05-25 01:06 UTC, evist0 commented on src/entities/posts/ui/post-reader/ui/header/index.tsx
> +          <p>
Я думаю что тег ‘p’ тут неуместен прям вообще никак

2022-05-27 20:16 UTC, default-razrab requested changes

2022-05-27 20:16 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/header/styled.ts
> +  p {
Не нужно использовать стили по именам тегов

2022-05-27 20:16 UTC, default-razrab commented on src/shared/ui/date-ago/styles.ts
> +import { Typography } from 'shared/ui/typography'
Зачем путь поменял?

2022-05-31 13:03 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/header/styled.ts
> +  p {
+++

2022-06-03 10:36 UTC, closed without merging