alkov-footer-layout-2
razrabs-media/journal pull request #97
Opened 2022-06-07 14:49 UTC by alkov-dev

ребейз

2022-06-09 16:21 UTC, default-razrab requested changes

2022-06-09 19:41 UTC, alkov-dev commented on src/shared/ui/footer/styled.ts
> +  a {
+++

2022-06-09 19:52 UTC, alkov-dev commented on src/shared/ui/footer/styled.ts
> +  width: 62%;
просто так по центру получается)

2022-06-09 19:52 UTC, alkov-dev commented on src/shared/ui/footer/styled.ts
> +export const StyledShareNav = styled(StyledNav)``
+++

2022-06-13 09:09 UTC, default-razrab commented
Нужно заребейзить

2022-06-13 11:57 UTC, closed without merging