linked twitter 2
razrabs-media/journal pull request #99
Opened 2022-06-07 15:19 UTC by alkov-dev

ребейз и исправление комментов

2022-06-07 15:22 UTC, default-razrab requested changes

2022-06-07 15:22 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
>            <ShareBlock>
Весь шаред блок бы вынести в отдельный компонент

2022-06-07 15:22 UTC, default-razrab commented on src/shared/ui/linked-share-button/index.tsx
> +  <a
Эти все параметры можно в Link засунуть насколько я знаю и не будет необходимость создавать тек a

2022-06-07 15:50 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
>            <ShareBlock>
+++

2022-06-07 16:34 UTC, default-razrab requested changes

2022-06-07 16:34 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
> +          <StyledShareBlock>
Весь шаред бокс Со всеми потрахами)

2022-06-09 10:10 UTC, alkov-dev commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
> +          <StyledShareBlock>
я не могу он переисполюзуется, и застилизован по разному в двух местах

2022-06-09 10:11 UTC, alkov-dev commented on src/shared/ui/linked-share-button/index.tsx
> +  <a
ну я на форуме прочитал, что используется a

2022-06-13 09:05 UTC, default-razrab commented on src/entities/posts/ui/post-reader/ui/floated-preview/index.tsx
> +          <StyledShareBlock>
не совсем сдли по большей части похожие

2022-06-30 13:26 UTC, closed without merging